on:
  push:
#    tags:
#    - v**
  workflow_dispatch:

jobs:
  compile_jar:
    name: Compile .jar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: javac -d ./build src/aoc2_converter/*.java
      - run: cd ./build
      - run: jar cfm ../release.jar ../src/Manifest.txt .
      - run: cd ..
      - uses: actions/upload-artifact@v6
        with:
          name: AoC2_Converter_${{github.ref_name}}.jar
          if-no-files-found: error
